### ISSUE TITLE
Google news

### ISSUE THREAD

**Issue by minkj1992** [filekit-co/wikitoday-front#6]
> https://publishercenter.google.com/

- [refs](https://support.google.com/news/publisher-center/answer/9545414?hl=en)
- https://support.google.com/news/publisher-center/answer/9545414?hl=en

<img width="1728" alt="Screen Shot 2023-08-12 at 1 10 02 AM" src="https://github.com/filekit-co/wikitoday-front/assets/37536298/3e911422-ec20-45d0-8294-5b7150c9bf71">

**Comment by seilylook** [comment]
![1](https://github.com/filekit-co/wikitoday-front/assets/48667219/ec962201-7197-4500-8390-9a6cf30f14d4)
